# Generated by Django 6.0.5 on 2026-05-22 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryman', '0002_deliveryman_created_at_deliveryman_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryman',
            name='password',
        ),
    ]
