# Generated by Django 6.0.5 on 2026-05-22 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryman', '0003_remove_deliveryman_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryman',
            options={'verbose_name_plural': 'Deliverymen'},
        ),
        migrations.RemoveField(
            model_name='deliveryman',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deliveryman',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
