# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryman', '0004_alter_deliveryman_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryman',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/delivery/'),
        ),
    ]
