# Generated by Django 6.0.5 on 2026-06-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryman', '0005_deliveryman_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_from', models.DecimalField(decimal_places=2, help_text='Order price range starts from (inclusive)', max_digits=10)),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, help_text='Order price range ends at (exclusive). Leave blank for unlimited upper bound.', max_digits=10, null=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, help_text='Delivery charge for this price range', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Delivery Charges',
                'ordering': ['price_from'],
                'unique_together': {('price_from', 'price_to')},
            },
        ),
    ]
