# Generated by Django 6.0.5 on 2026-06-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryman', '0006_deliverycharge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryCharge',
        ),
    ]
