# Generated by Django 6.0.5 on 2026-05-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-created_at'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='province',
            field=models.CharField(choices=[('Koshi', 'Koshi Province'), ('Madhesh', 'Madhesh Province'), ('Bagmati', 'Bagmati Province'), ('Gandaki', 'Gandaki Province'), ('Lumbini', 'Lumbini Province'), ('Karnali', 'Karnali Province'), ('Sudurpashchim', 'Sudurpashchim Province')], max_length=20, verbose_name='Province'),
        ),
    ]
