# Generated by Codex on 2026-05-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlocation', '0003_location_delivery_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChargeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('normal', 'Normal Delivery'), ('emergency', 'Emergency Fast Delivery')], max_length=20)),
                ('min_product_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_product_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_charge_rules', to='adminlocation.location', verbose_name='Location Zone')),
            ],
            options={
                'verbose_name': 'Delivery Charge Rule',
                'verbose_name_plural': 'Delivery Charge Rules',
                'ordering': ['location__province', 'location__city', 'min_product_total'],
            },
        ),
    ]
