# Generated by Django 6.0.5 on 2026-06-01 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlocation', '0004_deliverychargerule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='emergency_delivery_charge',
        ),
        migrations.RemoveField(
            model_name='location',
            name='normal_delivery_charge',
        ),
    ]
