# Generated by Django 6.0.5 on 2026-05-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpverification'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otpverification',
            name='users_otpve_email_61eaea_idx',
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
