# Generated by Django 6.0.5 on 2026-05-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_is_active_alter_users_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('assistant', 'Assistant'), ('warehousestaff', 'Warehouse Staff'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('delivery', 'Delivery Man')], default='buyer', max_length=20),
        ),
    ]
