# Generated by Django 6.0.5 on 2026-05-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='created_at',
        ),
    ]
