# Generated by Django 6.0.5 on 2026-05-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_username_otp_sellerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(unique=True),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
