# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
