# Generated by Django 6.0.5 on 2026-05-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_category_alter_product_description_and_more'),
    ]

    operations = [
    ]
