# Generated by Django 6.0.5 on 2026-06-08 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/views/')),
                ('image_type', models.CharField(choices=[('front', 'Front View'), ('back', 'Back View'), ('side', 'Side View'), ('top', 'Top View'), ('detail', 'Detail View'), ('other', 'Other View')], default='other', help_text='Type of view/angle', max_length=20)),
                ('view_number', models.PositiveIntegerField(default=1, help_text='View order (1, 2, 3, etc.)')),
                ('is_primary', models.BooleanField(default=False, help_text='Set as primary/default image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['view_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(help_text='Name of the color (e.g., Red, Blue, Black)', max_length=100)),
                ('color_code', models.CharField(default='#000000', help_text='Hex color code (e.g., #FF0000)', max_length=7)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Available quantity in this color')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Price difference for this color (can be positive or negative)', max_digits=12)),
                ('is_available', models.BooleanField(default=True, help_text='Whether this color is available for sale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Product Colors',
                'ordering': ['color_name'],
                'unique_together': {('product', 'color_name')},
            },
        ),
    ]
