# Generated by Django 6.0.5 on 2026-06-09 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_name'),
        ('product', '0007_productimage_productcolor'),
    ]

    operations = [
    ]
