# Generated by Codex on 2026-06-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
