# Generated by Django 6.0.6 on 2026-06-25 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_delete_productcolor_delete_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/views/')),
                ('image_type', models.CharField(choices=[('front', 'Front View'), ('back', 'Back View'), ('side', 'Side View'), ('top', 'Top View'), ('detail', 'Detail View'), ('other', 'Other View')], default='other', help_text='Type of view/angle', max_length=20)),
                ('view_number', models.PositiveIntegerField(default=1, help_text='View order (1, 2, 3, etc.)')),
                ('is_primary', models.BooleanField(default=False, help_text='Set as primary/default image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['view_number'],
            },
        ),
    ]
