# Generated by Django 6.0.5 on 2026-06-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('esewa', 'Esewa'), ('khalti', 'Khalti')], max_length=20),
        ),
    ]
