# Generated by Django 6.0.6 on 2026-06-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='billing_postal_code',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='shipping_postal_code',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='total_orders',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='total_spent',
        ),
    ]
