# Generated by Django 6.0.5 on 2026-05-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminperson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminperson',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
