# Generated by Django 6.0.5 on 2026-05-21 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminperson', '0002_adminperson_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminperson',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admin Person', 'verbose_name_plural': 'Admin Persons'},
        ),
        migrations.RemoveField(
            model_name='adminperson',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminperson',
            name='name',
        ),
        migrations.RemoveField(
            model_name='adminperson',
            name='role',
        ),
        migrations.RemoveField(
            model_name='adminperson',
            name='user_id',
        ),
        migrations.AddField(
            model_name='adminperson',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminperson',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
