# Generated by Django 6.0.5 on 2026-05-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminperson', '0003_alter_adminperson_options_remove_adminperson_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminperson',
            name='phone',
        ),
    ]
