# Generated by Django 6.0.5 on 2026-05-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_auto_20260517_1657'),
        ('productcategory', '0003_delete_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('d_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('free_shipping', 'Free Shipping'), ('buy_x_get_y', 'Buy X Get Y')], max_length=20, verbose_name='Discount Type')),
                ('d_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount Value')),
                ('applies_to', models.CharField(choices=[('all', 'All Products'), ('category', 'Specific Categories'), ('product', 'Specific Products')], default='all', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('buy_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('get_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='productcategory.category')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='product.product')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-created_at'],
            },
        ),
    ]
