# Generated by Django 6.0.5 on 2026-05-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productcategory', '0003_delete_subcategory'),
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='buy_quantity',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='get_quantity',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='products',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='applies_to',
            field=models.CharField(choices=[('all', 'All Products'), ('category', 'Specific Categories')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='productcategory.category', verbose_name='Select Categories'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='d_type',
            field=models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off')], max_length=20, verbose_name='Discount Type'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='minimum_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order value required to apply this promotion (Optional)', max_digits=10, null=True),
        ),
    ]
