# Generated by Django 6.0.5 on 2026-05-21 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_remove_promotion_buy_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='minimum_order_amount',
        ),
    ]
