# Generated by Django 6.0.5 on 2026-05-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_remove_promotion_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
