# Generated by Django 6.0.5 on 2026-05-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productcategory', '0003_delete_subcategory'),
        ('promotion', '0005_alter_promotion_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={},
        ),
        migrations.AlterField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='productcategory.category'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='d_type',
            field=models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='d_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
