# Generated by Django 6.0.5 on 2026-05-20 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productcategory', '0002_category_subcategory_delete_productcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
