# Generated by Django 6.0.6 on 2026-06-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('seller_accepted', 'Seller Accepted'), ('preparing', 'Preparing'), ('warehouse_processing', 'Warehouse Processing'), ('ready_for_delivery', 'Ready For Delivery'), ('delivery_assigned', 'Delivery Assigned'), ('delivery_accepted', 'Delivery Accepted'), ('picked_up', 'Picked Up'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('delivery_rejected', 'Delivery Rejected'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped')], default='pending', max_length=30),
        ),
    ]
